// PRODUCTION Deploy
### Get all contacts
GET https://three41wddw2.onrender.com/contacts/


### Get contact by id
GET https://three41wddw2.onrender.com/contacts/650e9057eda1c94561e08a3e


### Create contact
POST https://three41wddw2.onrender.com/contacts/ HTTP/1.1
content-type: application/json

{
    "firstName":"S",
    "lastName":"Gangster",
    "email":"test@test.com",
    "favoriteColor":"Blue",
    "birthday":"06/19/2000"
}

### PUT contact
PUT https://three41wddw2.onrender.com/contacts/6518a88d74ea6aa451515686 HTTP/1.1
content-type: application/json

{
    "firstName":"Sandman",
    "lastName":"G",
    "email":"test@gmail.com",
    "favoriteColor":"Cyan",
    "birthday":"12/11/22"
}


### DELETE contact
DELETE https://three41wddw2.onrender.com/contacts/6518a88d74ea6aa451515686 HTTP/1.1